AL-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update al bills"
  enabled: true
  environment: scrapers
  triggers:
#    - cron: 0 */6 * * ?
    - cron: 0 5 * * ?
  timeout_minutes: 360
  next_tasks:
    - AL-text

AL-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update al"
  enabled: true
  environment: scrapers

AL-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update al events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 8 1 * * ?
  timeout_minutes: 60
