IN-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update in bills"
  enabled: true
  environment: scrapers
  triggers:
   - cron: 0 */8 * * ?
#     - cron: 0 6 * * ?
  timeout_minutes: 720
  next_tasks:
    - IN-text

IN-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update in"
  enabled: true
  environment: scrapers

IN-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update in events"
  enabled: true
  environment: scrapers
  triggers:
   - cron: 0 3 * * ?
  timeout_minutes: 60
