KS-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ks bills"
  enabled: true
  environment: scrapers
  triggers:
#    - cron: 0 7,10,1,18 * * ?
    - cron: 0 7 * * ?
  timeout_minutes: 360
  next_tasks:
    - KS-text

KS-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update ks"
  enabled: true
  environment: scrapers

KS-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ks events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 10 3 * * ?
  timeout_minutes: 60
