MN-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update mn bills --realtime"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 0 */5 * * *
#    - cron: 0 1,8,11,17 * * ?
#   - cron: 0 7 * * ?
  timeout_minutes: 360
  next_tasks:
    - MN-text

MN-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update mn events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 20 * * * ?
  timeout_minutes: 55

MN-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update mn"
  enabled: true
  environment: scrapers
